source: src

host: 0.0.0.0
port: 4001

plugins:
  - jekyll-include-cache

exclude:
  - .idea
  - package.json
  # - tags.json
  - tags.html

collections:
  icons:
    output: false
  icons-outline:
    output: false
  icons-solid:
    output: false
